name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: [x64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild of solution
      run: |
           cd .\sourcecookifier\
           .\BUILD_ALL.BAT

    - name: zip artifacts for ${{ matrix.build_platform }}
      if: matrix.build_platform == 'Any CPU' && matrix.build_configuration == 'Release'
      run: |
           cd .\sourcecookifier\
           .\PACKAGE.BAT

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
          name: SourceCookifier.v0.10.0.${{ matrix.build_platform }}.bin.zip
          path: SourceCookifier.v0.10.0.${{ matrix.build_platform }}.bin.zip

    - name: Create release on tagging
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: SourceCookifier.v0.10.0.${{ matrix.build_platform }}.bin.zip

